In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
reviews = pd.read_csv('../data/processed_v2/olist_order_reviews_dataset.csv')

In [5]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 98673 entries, 0 to 98672
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                98673 non-null  str
 1   order_id                 98673 non-null  str
 2   review_score             98673 non-null  int64
 3   review_comment_title     11552 non-null  str
 4   review_comment_message   40774 non-null  str
 5   review_creation_date     98673 non-null  str
 6   review_answer_timestamp  98673 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.7 MB

In [13]:
master_orders = pd.read_csv('../data/master_begin2017/master_orders_begin2017.csv')

In [7]:
master_begin2017.info()

<class 'pandas.DataFrame'>
RangeIndex: 94819 entries, 0 to 94818
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       94819 non-null  str
 1   customer_id                    94819 non-null  str
 2   order_status                   94819 non-null  str
 3   order_purchase_timestamp       94819 non-null  str
 4   order_approved_at              94819 non-null  str
 5   order_delivered_carrier_date   94819 non-null  str
 6   order_delivered_customer_date  94819 non-null  str
 7   order_estimated_delivery_date  94819 non-null  str
 8   total_delivery_time            94819 non-null  int64
 9   seller_prep_time               94819 non-null  int64
 10  pure_shipping_time             94819 non-null  int64
 11  delivery_accuracy              94819 non-null  int64
 12  estimated_wait_time            94819 non-null  int64
 13  is_delayed                     94819 non-null  int64
 14  purchase_hour                  94819 non-null  int64
 15  purchase_dayofweek             94819 non-null  str
 16  purchase_month                 94819 non-null  int64
 17  is_weekend                     94819 non-null  bool
 18  delivery_speed_type            94819 non-null  str
 19  item_count                     94819 non-null  int64
 20  seller_count                   94819 non-null  int64
 21  total_price                    94819 non-null  float64
 22  total_freight                  94819 non-null  float64
 23  payment_count                  94819 non-null  float64
 24  payment_total                  94819 non-null  float64
 25  max_installments               94819 non-null  float64
 26  main_payment_type              94819 non-null  str
 27  review_score                   94183 non-null  float64
 28  review_comment_message         38175 non-null  str
 29  customer_unique_id             94819 non-null  str
 30  customer_city                  94819 non-null  str
 31  customer_state                 94819 non-null  str
dtypes: bool(1), float64(6), int64(10), str(15)
memory usage: 45.5 MB

In [14]:
origin_orders = pd.read_csv('../data/raw/olist_orders_dataset.csv')

In [11]:
origin_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [12]:
origin_orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [16]:
master_sellers = pd.read_csv('../data/master_begin2017/master_sellers_begin2017.csv')

In [17]:
master_sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seller_id          2930 non-null   str
 1   total_orders       2930 non-null   int64
 2   total_items        2930 non-null   int64
 3   total_revenue      2930 non-null   float64
 4   total_freight      2930 non-null   float64
 5   avg_review_score   2930 non-null   float64
 6   review_count       2930 non-null   int64
 7   five_star_count    2930 non-null   int64
 8   one_star_count     2930 non-null   int64
 9   avg_delivery_days  2930 non-null   float64
 10  delay_count        2930 non-null   float64
 11  first_order_date   2930 non-null   str
 12  last_order_date    2930 non-null   str
 13  total_gmv          2930 non-null   float64
 14  five_star_rate     2930 non-null   float64
 15  one_star_rate      2930 non-null   float64
 16  delay_rate         2930 non-null   float64
 17  seller_city        2930 non-null   str
 18  seller_state       2930 non-null   str
dtypes: float64(9), int64(5), str(5)
memory usage: 670.1 KB

In [18]:
geo = pd.read_csv('../data/processed_v2/olist_geolocation_dataset.csv')
geo.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [19]:
geo.groupby('geolocation_state')[['geolocation_lat','geolocation_lng']].mean()

                   geolocation_lat  geolocation_lng
geolocation_state
AC                       -9.702555       -68.451852
AL                       -9.599729       -36.052017
AM                       -3.349336       -60.537430
AP                        0.086025       -51.234304
BA                      -13.049361       -39.560649
CE                       -4.363151       -39.004140
DF                      -15.810885       -47.969630
ES                      -20.105145       -40.503183
GO                      -16.577645       -49.334195
MA                       -3.798997       -44.818627
MG                      -19.864647       -44.421615
MS                      -20.765006       -54.532140
MT                      -14.156482       -55.708956
PA                       -2.631213       -49.485862
PB                       -7.088298       -35.821678
PE                       -8.179098       -35.758866
PI                       -5.754989       -42.509541
PR                      -24.793607       -50.879662
RJ                      -22.743477       -43.155540
RN                       -5.856702       -35.990079
RO                      -10.341289       -62.720579
RR                        2.717100       -60.672866
RS                      -29.679191       -52.032652
SC                      -27.222486       -49.617937
SE                      -10.866199       -37.181169
SP                      -23.155308       -47.084074
TO                       -9.503700       -48.348661